<?php

/**
 * @file
 * FitLife Checkout Styling.
 */

/**
 * Implements hook_page_attachments().
 */
function fitlife_checkout_style_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'fitlife_checkout_style/cart-checkout';
}

/**
 * Implements hook_theme_registry_alter().
 */
function fitlife_checkout_style_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['commerce_checkout_completion_message'])) {
    $path = \Drupal::service('extension.list.module')->getPath('fitlife_checkout_style');
    $theme_registry['commerce_checkout_completion_message']['path'] = $path . '/templates';
  }
}
